# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: pamador-web CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Clear .next cache with sudo
      run: sudo rm -rf .next/cache
    - uses: actions/checkout@v4
    - name: create env.production file
      run: |
        touch .env.production
        echo NEXT_PUBLIC_IMAGE_STORAGE_URI="${{ secrets.NEXT_PUBLIC_IMAGE_STORAGE_URI }}" >> .env.production
        echo NEXT_PUBLIC_GRAPHQL_URI="${{ secrets.NEXT_PUBLIC_GRAPHQL_URI }}" >> .env.production
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - run: sudo pm2 stop pamador-web
    - run: yarn build
    - run: sudo pm2 restart pamador-web
